### ISSUE TITLE
Support for YUV

### ISSUE THREAD

**Issue by axolotl-logic** [tobspr/GLSL-Color-Spaces#1]
I'm using this in a project and I'd love support for YUV. Are you accepting pull requests?

**Comment by axolotl-logic** [comment]
Particularly my project uses YUV888

**Comment by tobspr** [comment]
Sure, feel free to make a PR! :)

**Comment by axolotl-logic** [comment]
Ha, I meant YUV444. I also ended up learning more about YUV and realizing what I likely wanted was YCbCr and YUV is meant to be for analog signals, furthermore that YUV444 doesn't actually make sense in the context of GLSL. I  implemented YUV anyways (with BT.601 and BT.709 weights) and will add YCbCr to the pull request before submitting.

**Comment by axolotl-logic** [comment]
See pull request https://github.com/tobspr/GLSL-Color-Spaces/pull/2
I also changed X -> d in the documentation because X vs x was hard to distinguish at a glance.

**Comment by tobspr** [comment]
Merged it, thanks for your work! :)
